### ISSUE TITLE
Readme.md Image Thread

### ISSUE THREAD

**Issue by CodeKi0303** [boostcampaitech4lv23cv3/level2_objectdetection_cv-level2-cv-16#1]
![image](https://user-images.githubusercontent.com/25689849/214489441-4c44939a-0ba7-4d3a-b829-61db94e7ebb7.png)

**Comment by FIN443** [comment]
![7645ad37-9853-4a85-b0a8-f0f151ef05be](https://user-images.githubusercontent.com/70796031/214493481-2d7a678b-f4a5-4620-9efd-9eb2bb505209.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214493547-66f629bb-3864-4bf1-a997-31586c82b4ee.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214493814-4ee7cef2-a8fd-4264-a795-ea59a71b50d0.png)

**Comment by revanZX** [comment]
![image](https://user-images.githubusercontent.com/25689849/214489655-503211b4-5d69-45ce-a330-40c1d1b53f60.png)

**Comment by revanZX** [comment]
![image](https://user-images.githubusercontent.com/25689849/214489655-503211b4-5d69-45ce-a330-40c1d1b53f60.png)

**Comment by revanZX** [comment]
![image](https://user-images.githubusercontent.com/25689849/214489655-503211b4-5d69-45ce-a330-40c1d1b53f60.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214494176-0948b0b5-ba8c-4782-b03b-8081c6f7facd.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214494267-850a2497-1317-4aeb-aa10-39fd504596f8.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214494486-ba4ef612-af00-4574-b6e2-253cdc08c390.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214494581-2e84ac05-cd7f-4c7a-83d2-a918e5f8f295.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214495149-60c3b0b7-cae0-4e6c-b65d-a7a1ce801ffa.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214495508-2f73b8a1-6eae-4c55-b4a9-4abccafb9701.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214497415-911bfdc0-b86a-4fc7-889e-4db4513674f4.png)

**Comment by choipp** [comment]
![image](https://user-images.githubusercontent.com/103131249/214497553-a8b6c95f-ae49-4151-9cf9-74cb85016704.png)

**Comment by CodeKi0303** [comment]
![image](https://user-images.githubusercontent.com/25689849/214497620-549d2e54-c681-4233-b9a3-fbe3bd3c5fd1.png)
